name: CI

on:
  push:
    branches: [ saikyohopz ]
  pull_request:
    branches: [ saikyohopz ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      
      - name: Setup SourcePawn Compiler
        uses: rumblefrog/setup-sp@master
        with:
          version: '1.10.x'

      - name: Compile
        run: |
          cd $GITHUB_WORKSPACE/addons/sourcemod/scripting
          for file in s*.sp; do spcomp -i./include $file; done;
